### ISSUE TITLE
Selfhost this application

### ISSUE THREAD

**Issue by RitchiS99** [mmcardle/django_builder#212]
The docs about selfhosting this application are a little bit difficult for my understanding. The goal is to selfhost this application.
Best would be a hosting with local database, but i dont understand how can i define that it shall use a local database like the postgresql defined in the docker-compose.yml but my setup is also not working with the firestore database.

What i understand until now: if i want to start the firebase application i need to change the public attribute in the hosting section to use packages/djangobuilder.io/dist

now when i start the application and use the firestore database i am able to create a project, but the version keeps empty and my js log is showing me: `TypeError: Cannot read properties of undefined (reading 'name')`
But okay the project is created and if i refresh the site the django version is correct and the project-name.

Now i can create an app but if i want to create a model for this, it keeps throwing me the error `Uncaught (in promise) FirebaseError: Function CollectionReference.doc() cannot be called with an empty path` and the model is never created even after a bunch of refreshs. The apps cant be deleted and the download is even not working. What am i doing wrong?

**Comment by mmcardle** [comment]
Hi @RitchiS99 

Thanks for the feedback, no one has ever asked about self hosting so that is why the docs are a little sparse on details 
So the only way currently to use the application is with a firebase backend. The docker-compose postgres it just for testing the Django application after you have downloaded it.

So just to check, you have setup a Firebase application called 'development' and then run `make deploy name=development`

Then run `yarn run dev` and navigated to http://127.0.0.1:8080/#/home and you are seeing the errors you describe.

You should not need to change any attributes in the hosting section, but I will checkout a new version and try to set it up from fresh just in case there is something in my local environment that I have missed from the process.

**Comment by RitchiS99** [comment]
Thank you very much for your quick answer, so we will try this. Our firebase application wasn't named development, maybe this was the error.

Another question: Your new commits looks like you are doing a code restructure. Is it rational to deploy this application on my server now, or will you change the complete structure in near future, so it would be rational to wait until your restructure?

Greetings

**Comment by mmcardle** [comment]
Hi @RitchiS99 

Yes I think it would be wise to either 

- use a more stable version before the refactor if you do want to deploy and test it.
- or wait until after I have the refactor is complete

I have created a branch which is much more stable called `pre-monorepo` https://github.com/mmcardle/django_builder/tree/pre-monorepo` if you do wish to continue now.

**Comment by mmcardle** [comment]
Hi @RitchiS99 

The latest changes to the `master` branch should be more stable now. Let me know if it works for you.

**Comment by RitchiS99** [comment]
Hi, thank you alot. Now I was able to bring it to work, but there are still a few issues left. The issues i found were, that deletion of models and of fields is not working. Additionally i have two feature requests:

- General: To integrate translation, so it's auto added in the models.py and the views (import and the declaration)
- For selfhosting: The possibility to use a self hosted database


I deployed this tool via docker-compose, so i will share my docker-compose.yml. If you want to add this to the repo feel free:
```
version: '3.9'

volumes:
  db:

services:

  djangobuilder:
    container_name: django-builder-container
    image: node:18.20.6
    restart: unless-stopped
    environment:
      - FIREBASE_TOKEN={YOUR_FIREBASE_TOKEN}
    volumes:
      - ./django_builder:/app
      - ./firebase.json:/app/firebase.json
      - ./.env:/app/packages/djangobuilder.io/.env
    working_dir: /app
    command: bash -c "apt-get update && apt-get install -y curl gnupg && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && echo 'deb https://dl.yarnpkg.com/debian/ stable main' | tee /etc/apt/sources.list.d/yarn.list && apt-get update && apt-get install -y yarn && yarn global add firebase-tools && yarn install && yarn build_io && firebase serve --project {YOUR_PROJECT_NAME} --host 0.0.0.0 --port 8008 --config firebase.json"

    ports:
      - 8008:8008

```

The firebase.json would be:
```
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "hosting": {
    "public": "packages/djangobuilder.io/dist/",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "db4/**",
        "destination": "/db4/index.html"
      },
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
  "emulators": {
    "firestore": {
      "port": 8080
    },
    "hosting": {
      "port": 8008
    },
    "ui": {
      "enabled": true
    }
  }
}
``` 
And fill out your .env File like the one in the repo (google analytics is optional).

Maybe this will help someone else too
